### ISSUE TITLE
Runit repeats the start operation on service exception

### ISSUE THREAD

**Issue by rpiesnikowski** [phusion/baseimage-docker#208]
Hi,
I have problem with automatic respawn of service inside docker container when service occur exception. 
Is this supposed behaviour? - I thought when service throws exception runit deamon should not restart service for infinity.
Can I stop respawning that service? 

### nodejs app
```javascript
//This will fail
var http = require('httep');
// Configure our HTTP server to respond with Hello World to all requests.
var server = http.createServer(function (request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.end("Hello World\n");
});
// Listen on port 8000, IP defaults to 127.0.0.1
server.listen(8000);
// Put a friendly message on the terminal
console.log("Server running at http://127.0.0.1:8000/");
```
### Dockerfile
```
ADD . /app
RUN chown -R daemon:daemon /app
RUN mkdir /etc/service/app
ADD ./app.sh /etc/service/app/run
RUN chmod +x /etc/service/app/run
```
### app.sh
```
#!/bin/bash
cd /app
exec /sbin/setuser daemon ./helloWorld.js
```
### Running
```
 sudo docker logs 14757b9fb34e
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 96
module.js:340
    throw err;
          ^
Error: Cannot find module 'httep'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app/helloWorld.js:33:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
### Inspecting
```
 sudo nsenter -t $(sudo docker inspect --format '{{ .State.Pid }}' 14757b9fb34e) -m -u -i -n -p -w
 run: app: (pid 1161) 0s
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 1s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 1s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
down: app: 0s, normally up, want up
root@14757b9fb34e:/# sv status app
run: app: (pid 1227) 0s
root@14757b9fb34e:/# sv down app
root@14757b9fb34e:/# sv status app
down: app: 2s, normally up
root@14757b9fb34e:/# sv status app
down: app: 4s, normally up
```

**Comment by FooBarWidget** [comment]
This is how Runit is supposed to work. If your app exits for whatever reason, Runit respawns it.

If you want the container to shut down after the app exits, use this approach (without using Runit to supervise your app): https://github.com/phusion/baseimage-docker#oneshot
